uwc-docs: Updated User Guide for 1.6 release.
open-edge-insights/uwc-docs pull request #18
Opened 2021-09-03 12:44 UTC by aditisa1

Modified for UWC 1.6

Signed-off-by: aditi saxena <aditi.saxena@intel.com>

2021-09-03 17:40 UTC, nagdeepgk requested changes
@aditisa1 The data persistence changes from softdel's PR https://github.com/open-edge-insights/uwc-docs/pull/7, needs to be added to this, as mentioned earlier.
Request to plz add the changes.

2021-09-03 17:40 UTC, nagdeepgk commented on source/Pages/page_02.rst
> +    • Integrated InfluxDBConnector & Telegraf services of EII's TICK stack timeseries services with UWC.
In deployment https://open-edge-insights.github.io/uwc-docs/Pages/page_02.html, somehow these bullet points are not visible. Can we add bullet points or numericals ?

2021-09-03 17:40 UTC, nagdeepgk commented on docs/_sources/Pages/page_04.rst.txt
> +    •	git clone https://github.com/open-edge-insights/eii-tools.git IEdgeInsights/tools --branch=v2.6
we also need to add 2 uwc repos with v1.6 tag, as mentioned. lets add them.

2021-09-03 17:40 UTC, nagdeepgk commented on docs/_sources/Pages/page_04.rst.txt
> +    4) Basic UWC micro-services with Sparkplug-Bridge and no KPI-tactic Application
there are only 4 use cases mentioned here. we need to update thi sfor our 8 use cases.

2021-09-03 17:43 UTC, nagdeepgk commented
@aditisa1 The data persistence changes from softdel's PR https://github.com/open-edge-insights/uwc-docs/pull/7 , needs to be added to this, as mentioned earlier.
Request to plz add the changes.

2021-09-03 18:07 UTC, aditisa1 commented
> @aditisa1 The data persistence changes from softdel's PR #7 , needs to be added to this, as mentioned earlier.
> Request to plz add the changes.

@nagdeepgk I made those changes I copied it . It may be possible that I moved the files to make page_02 (release notes) because which file structure is different. Did I miss anything?

2021-09-03 18:13 UTC, aditisa1 commented on source/Pages/page_02.rst
> +    • Integrated InfluxDBConnector & Telegraf services of EII's TICK stack timeseries services with UWC.
![doc](https://user-images.githubusercontent.com/70901457/132049491-81901853-f271-446c-b107-8e920f27bb0c.JPG)
![vs](https://user-images.githubusercontent.com/70901457/132049492-5884dd84-0a92-42de-b71a-6c956faac508.JPG)

2021-09-03 18:14 UTC, aditisa1 commented on source/Pages/page_02.rst
> +    • Integrated InfluxDBConnector & Telegraf services of EII's TICK stack timeseries services with UWC.
Hi Nagdeep 
i see that is happening in all the file above is page_01.rst

2021-09-06 07:31 UTC, nagdeepgk commented on source/Pages/page_02.rst
> +* In UWC-v1.6, KPI bug of random crashing and zero bugs is fixed
rephrase like this:
KPI bugs on random KPI-app crashing, non-linearity of bad records versus control loop count addressed.

2021-09-06 12:34 UTC, nagdeepgk approved these changes

2021-09-06 12:36 UTC, nagdeepgk approved these changes

2021-09-06 12:41 UTC, merged